apiVersion: v1
kind: Pod

metadata:
  name: todo-backend

spec:
  containers:
    - name: backend
      image: rathod3232/to-do-backend:v1

      ports:
        - containerPort: 5000

      env:
        - name: PORT
          value: "5000"

        - name: JWT_SECRET
          value: "TODO"

        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/todoapp"